# Generated by Django 4.1 on 2022-08-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogslider',
            options={'verbose_name_plural': 'Blog Slider'},
        ),
        migrations.AlterModelOptions(
            name='contactslider',
            options={'verbose_name_plural': 'Contact Slider'},
        ),
        migrations.AlterModelOptions(
            name='homesliderone',
            options={'verbose_name_plural': 'Home Slider One'},
        ),
        migrations.AlterModelOptions(
            name='homesliderthree',
            options={'verbose_name_plural': 'Home Slider Three'},
        ),
        migrations.AlterModelOptions(
            name='homeslidertwo',
            options={'verbose_name_plural': 'Home Slider Two'},
        ),
        migrations.AlterModelOptions(
            name='menuslider',
            options={'verbose_name_plural': 'Menu Slider'},
        ),
        migrations.AlterModelOptions(
            name='storyslider',
            options={'verbose_name_plural': 'Story Slider'},
        ),
    ]
