# Generated by Django 4.1 on 2022-08-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='icon',
            new_name='favicon',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='icon/'),
        ),
    ]
