# Generated by Django 4.1 on 2022-08-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='contact_id',
            new_name='team_id',
        ),
    ]
