# Generated by Django 4.1 on 2022-08-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_contact_id_teammember_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('small_description', models.CharField(max_length=400)),
                ('content', models.TextField()),
            ],
        ),
    ]
