# Generated by Django 4.1 on 2022-08-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='breakfastMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('total_reviews', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menuimage/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dinnerMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('total_reviews', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menuimage/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='launchMenu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('total_reviews', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='menuimage/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='specialMenu',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.breakfastmenu')),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dinnermenu')),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.launchmenu')),
            ],
        ),
    ]
