# Generated by Django 4.1 on 2022-08-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='comment_id',
            new_name='reserve_id',
        ),
    ]
