# Generated by Django 4.1 on 2022-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About Page Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Blog Page Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact Page Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Home Page Meta Tags',
            },
        ),
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('meta_keyword', models.CharField(max_length=200)),
                ('meta_description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Menu Page Meta Tags',
            },
        ),
    ]
