# Generated by Django 4.1 on 2022-08-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubs',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('emails', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Email Subscribers',
            },
        ),
    ]
